experiment: toaa-evaluations

wandb:
  entity: "sbordt-University of Tübingen"

model: sbordt/OLMo-2-1B-Exp

evaluation:
  evaluations:
    - name: insertion_likelihood
      script: train-once-answer-all/insertion_likelihood.py
