experiment: toaa-evaluations

wandb:
  name: test-insertion-likelihood-7x
  entity: "sbordt-University of Tübingen"

model: sbordt/OLMo-2-1B-7x

evaluation:
  evaluations:
    - name: insertion_likelihood_knowledge_acquisition
      script: train-once-answer-all/insertion_likelihood.py
      args:
        experiment: knowledge-acquisition

    - name: insertion_likelihood_memorization_patterns_plain_1x
      script: train-once-answer-all/insertion_likelihood.py
      args:
        experiment: memorization-patterns-plain-1x

    - name: insertion_likelihood_muse_news
      script: train-once-answer-all/insertion_likelihood.py
      args:
        experiment: muse-news

    - name: insertion_likelihood_iid_replacements_ratio
      script: train-once-answer-all/insertion_likelihood.py
      args:
        experiment: iid-replacements-ratio
