experiment: test-hf-checkpoint-download

wandb:
  name: test-hf-checkpoint-download
  entity: "sbordt-University of Tübingen"

framework: olmo

model:
  config: "${OLMO_REPO}/configs/official-0425/OLMo2-1B-stage1.yaml"
  checkpoint_hf_repo: "sbordt/test-checkpoint-upload"
  checkpoint_hf_revision: "step100000-unsharded"
  checkpoint_save_path: "/mnt/lustre/work/luxburg/sbordt10/single_training_run/test-hf-checkpoint-download"

training:
  num_steps: 10
  args:
    device_train_microbatch_size: 4
    evaluators: []
    data.num_workers: 8
    model.flash_attention: false
    fused_loss: false
